export EDITOR='nvim'
export LANG=en_US.UTF-8

ANTIGEN_HOME=~/.antigen
USER_OPT_DIR=~/opt

# If we're using WSL2.
if [[ $(grep -i Microsoft /proc/version) ]]; then
    HOST=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
    # WSL2 doesn't have a GUI.
    # use $TTY instead of `$(tty)` or `echo $GPG_TTY` yields "no a tty"
    # Ref: https://unix.stackexchange.com/questions/608842/zshrc-export-gpg-tty-tty-says-not-a-tty
    export GPG_TTY=$TTY
else
    HOST=127.0.0.1
fi

# proxy
export socks_proxy="socks5://${HOST}:7890"

export GOPROXY=https://goproxy.cn
export GOPATH=${HOME}/.go

# man-pages
export MANPAGER='bash -c "col -bx | batcat -pl man --theme=Monokai\ Extended"'
export MANROFFOPT='-c'

# alias
alias vim="nvim"
alias vi="nvim"
alias nj="ninja"
alias pc="proxychains"
alias tmn="tmux new -s"
alias tma="tmux attach -t"
alias tml="tmux list-sessions"
alias tmk="tmux kill-session -t"
alias cmk="cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ../"
# Download music from youtube
alias ytb-music="youtube-dl --ignore-errors --output '%(title)s.%(ext)s' --extract-audio --audio-format mp3"
# Play music with no gui
alias ffplay="ffplay -nodisp -autoexit"
# FIXME: This only work for Ubuntu.
alias open="xdg-open"

if [ ! -d ${USER_OPT_DIR} ]; then
    mkdir ${USER_OPT_DIR}
else
    for dir in $(ls ${USER_OPT_DIR}); do
        PATH=${USER_OPT_DIR}/${dir}/bin:${PATH}
    done
fi

export PATH=${PATH}:~/.local/bin:/usr/local/cuda/bin

if [ ! -d ${ANTIGEN_HOME} ]; then
    echo "antigen is not available, install it now..."
    mkdir ${ANTIGEN_HOME}
    curl -sL git.io/antigen > ${ANTIGEN_HOME}/antigen.zsh
fi

if [[ $(cat ${ANTIGEN_HOME}/antigen.zsh | wc -l) == 0 ]]; then
    echo "antigen failed to install!"
    rm -rf ${ANTIGEN_HOME}
    exit 1
else
    source ${ANTIGEN_HOME}/antigen.zsh
    antigen use oh-my-zsh
    antigen bundle vi-mode
    antigen bundle git
    antigen bundle fzf
    antigen bundle zsh-users/zsh-autosuggestions
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle romkatv/powerlevel10k
    antigen theme romkatv/powerlevel10k
    antigen apply
fi

function work {
    if [[ -n "${TMUX}" ]]
    then
        return 0
    fi
    tmux ls -F '#{session_name}' |
    fzf --bind=enter:replace-query+print-query |
    read session && tmux attach -t ${session:-default} || tmux new -s ${session:-default}
}

function llvm-patch-apply() {
    curl -sL https://reviews.llvm.org/${1}\?download\=true | git apply -
}

# Set additional proxies, some stuff need it but others seem to be
# broken if these are set. So make it optional.
function set-proxy() {
    export http_proxy="http://${HOST}:7890"
    export https_proxy="http://${HOST}:7890"
}
