export EDITOR='nvim'
export LANG=en_US.UTF-8

ANTIGEN_HOME=${HOME}/.antigen
USER_OPT_DIR=${HOME}/opt

# If we're using WSL2.
if [[ $(grep -i Microsoft /proc/version) ]]; then
    HOST=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
    # WSL2 doesn't have a GUI.
    # use $TTY instead of `$(tty)` or `echo $GPG_TTY` yields "no a tty"
    # Ref: https://unix.stackexchange.com/questions/608842/zshrc-export-gpg-tty-tty-says-not-a-tty
    export GPG_TTY=$TTY
else
    HOST=127.0.0.1
fi

# proxy
export socks_proxy="socks5://${HOST}:7890"

# Set additional proxies, some stuff need it but others seem to be
# broken if these are set. So make it optional.
function set-proxy() {
    export http_proxy="http://${HOST}:7890"
    export https_proxy="http://${HOST}:7890"
}

export GOPROXY=https://goproxy.cn
export GOPATH=${HOME}/.go
export PATH=${PATH}:~/.local/bin:/usr/local/cuda/bin

if [ -f "/etc/arch-release" ]; then
    export GPG_TTY=$TTY
fi

# alias
alias vi="nvim"
# FIXME: This only work for Ubuntu.
alias open="xdg-open"

if [ ! -d ${USER_OPT_DIR} ]; then
    mkdir ${USER_OPT_DIR}
else
    for dir in $(ls ${USER_OPT_DIR}); do
        PATH=${USER_OPT_DIR}/${dir}/bin:${PATH}
    done
fi

function work {
    if [[ -n "${TMUX}" ]]
    then
        return 0
    fi
    tmux ls -F '#{session_name}' |
    fzf --bind=enter:replace-query+print-query |
    read session && tmux attach -t ${session:-default} || tmux new -s ${session:-default}
}

if [[ ! -d ${ANTIGEN_HOME} ]]; then
    mkdir ${ANTIGEN_HOME}
    echo "antigen is not found!"
    echo "Try:"
    echo "$ curl -sL git.io/antigen > ${ANTIGEN_HOME}/antigen.zsh"
    echo "$ source ${ANTIGEN_HOME}/antigen.zsh"
    echo "source ~/.zshrc"
else
    source ${ANTIGEN_HOME}/antigen.zsh
    antigen use oh-my-zsh
    antigen bundle vi-mode
    antigen bundle git
    antigen bundle fzf
    antigen bundle zsh-users/zsh-autosuggestions
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle romkatv/powerlevel10k
    antigen theme romkatv/powerlevel10k
    antigen apply
fi
