export EDITOR='nvim'

USER_OPT_DIR=${HOME}/opt

export GPG_TTY=$TTY

# HOST_ADDR=127.0.0.1
# PORT=7890

# proxy
# export socks_proxy="socks5://${HOST_ADDR}:${PORT}"

# Set additional proxies, some stuff need it but others seem to be
# broken if these are set. So make it optional.
# function set-proxy() {
#     export http_proxy="http://${HOST_ADDR}:${PORT}"
#     export https_proxy="http://${HOST_ADDR}:${PORT}"
# }

export GOPROXY=https://goproxy.cn
export GOPATH=${HOME}/.go
export PATH=${PATH}:${HOME}/.local/bin:/usr/local/cuda/bin

# alias
alias vi="nvim"
# FIXME: This only work for Ubuntu.
# alias open="xdg-open"

alias logout="gnome-session-quit --logout --force"

if [ -d ${USER_OPT_DIR} ]; then
    for dir in $(ls ${USER_OPT_DIR}); do
        PATH=${USER_OPT_DIR}/${dir}/bin:${PATH}
    done
fi

function t {
    if [[ -n "${TMUX}" ]]
    then
        return 0
    fi
    tmux ls -F '#{session_name}' |
    fzf --bind=enter:replace-query+print-query |
    read session && tmux attach -t ${session:-default} || tmux new -s ${session:-default}
}

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh